// rulebooks data
const rulebooks = [
  {
    id: 'staff-rules',
    name: '员工守则',
    desc: '恭喜入职精神病院，身为我院普通工作人员，请遵守以下规则。',
    items: [
      { id: 'staff-01', num: 1, title: '听从领导安排', content: '听从领导的安排，尽量不要违抗。' },
      { id: 'staff-02', num: 2, title: '院长权威', content: '院长是本院地位最高者，不得违抗他的命令。' },
      { id: 'staff-03', num: 3, title: '准时备药', content: '每天必须准时给病人准备好药物。' },
      { id: 'staff-04', num: 4, title: '监督用餐', content: '按时监督病人用餐。' },
      { id: 'staff-05', num: 5, title: '胡萝卜干异常', content: '病人不会吃胡萝卜干，若发现，请立即带走，并汇报给高层。' },
      { id: 'staff-06', num: 6, title: '单人间异常', content: '病人都是单人间，若有病人说有其他人在他房间内，立即带去医药房。' },
      { id: 'staff-07', num: 7, title: '禁止串房', content: '病人不得擅自去其他病房，若发现，请立即带回他的房间。' },
      { id: 'staff-08', num: 8, title: '配合审查', content: '院长有时候会来病人区审查工作，请配合。' },
      { id: 'staff-09', num: 9, title: '隐藏异常', content: '如果你在院里看到不正常的病人和现象，请不要被它发现，装成很正常的样子并上报给高层。' },
      { id: 'staff-10', num: 10, title: '药物专属', content: '病人的药是根据他们量身定制的，不要分发错误。' },
      { id: 'staff-11', num: 11, title: '黑色病号服', content: '若看见黑色病号服的病人，请不要和他对视，立即带去药房。' },
      { id: 'staff-12', num: 12, title: '保管工作牌', content: '请不要被病人夺走工作牌，这是你的身份证明。' },
      { id: 'staff-13', num: 13, title: '午夜查房', content: '十二点的后，请去查房，若发现没睡着的病人，带到医药房。' },
      { id: 'staff-14', num: 14, title: '无视吵闹', content: '病人如果在公共场合大吵大闹的，请无视。' },
      { id: 'staff-15', num: 15, title: '夜间无人', content: '晚上十点后不会有工作人员。' },
      { id: 'staff-16', num: 16, title: '红色药物', content: '病人的药都是红色的，请监督，并保证他们已经吃下去。' },
      { id: 'staff-17', num: 17, title: '禁止动物', content: '我院不会出现任何一只动物。' },
      { id: 'staff-18', num: 18, title: '菜地禁区', content: '菜地除高层外，任何人不得入内，若发现，格杀勿论。' },
      { id: 'staff-19', num: 19, title: '食堂高层', content: '若看见高层领导在食堂，请无视。' },
      { id: 'staff-20', num: 20, title: '高层不会来食堂', content: '高层领导不会来食堂，不会，若发现，请立即去找院长。' },
      { id: 'staff-21', num: 21, title: '安全部', content: '若遇到安全部的人，请无视。' },
      { id: 'staff-22', num: 22, title: '特殊镜子', content: '我院的镜子很特殊，有空去看看吧。' },
      { id: 'staff-23', num: 23, title: '照镜子的人', content: '病人不会去照镜子，照镜子的不是病人，请联系院长。' },
      { id: 'staff-24', num: 24, title: '院长办公室位置', content: '若有病人问院长办公室的位置，请如实回答。' },
      { id: 'staff-25', num: 25, title: '没有音乐', content: '医院不会放音乐。' },
      { id: 'staff-26', num: 26, title: '四楼卫生间', content: '四楼卫生间非工作人员不得入内。' },
      { id: 'staff-27', num: 27, title: '禁止外卖', content: '请不要在医院点外卖，医院的伙食非常好。' },
      { id: 'staff-28', num: 28, title: '忠诚病院', content: '你是病院的一份子，一部分，请不要背叛医院。' }
    ]
  },
  {
    id: 'security-rules',
    name: '安全部守则须知',
    desc: '安全部人员需遵守的工作须知与异常防范指南。',
    items: [
      { id: 'sec-01', num: 1, title: '上班时间', content: '你得上班时间为早七到晚九，请不要早到或晚退。' },
      { id: 'sec-02', num: 2, title: '奇怪的东西', content: '病院有时会跑出来一些奇怪东西，不要担心，你不会遭受攻击的。' },
      { id: 'sec-03', num: 3, title: '菜地和水池', content: '请不要去往菜地和水池，那里空寂无物，不会有东西去的。' },
      { id: 'sec-04', num: 4, title: '五楼和地下楼层', content: '病院设有五楼和地下楼层但不能进入，请防范病人进入。' },
      { id: 'sec-05', num: 5, title: '与病人交谈', content: '病人们都很宽容，但请在下班时交谈。' },
      { id: 'sec-06', num: 6, title: '院长', content: '院长是个很友好的人，你感到迷茫时去找她吧。' },
      { id: 'sec-07', num: 7, title: '镜子和厕所', content: '四楼的镜子和厕所请时刻挂上“闲人免进”，镜子请遮挡好。' },
      { id: 'sec-08', num: 8, title: '不要沉迷音乐', content: '在病人们听音乐时，请不要沉迷，记住你是个职工。' },
      { id: 'sec-09', num: 9, title: '打卡画框', content: '每天打卡的地方有个画框，是院长专门为激励你们打卡做的，请积极配合，不要迟到哦！' },
      { id: 'sec-10', num: 10, title: '小动物', content: '病院很受小动物们欢迎，每一天都有跑进来玩，请不要伤害它们。' },
      { id: 'sec-11', num: 11, title: '不要撸猫', content: '如果看见猫咪突然出现至你身后蹭人时，请不要撸猫，会扣钱。' },
      { id: 'sec-12', num: 12, title: '受伤就医', content: '当你们受伤时请直接前往医疗部，他会治疗你们。' },
      { id: 'sec-13', num: 13, title: '保持清醒', content: '保持清醒，都是幻觉，不要听不要想。' },
      { id: 'sec-14', num: 14, title: '防范越院', content: '病人们总是很调皮，越院之事常有发生，请注意防范。' },
      { id: 'sec-15', num: 15, title: '科学怪人', content: '院内有位科学怪人，你所见得都是AI生成，不要害怕，请友善对待每一位AI。' },
      { id: 'sec-16', num: 16, title: '奇怪的钟表', content: '院内有个奇怪的钟表，钟表指示时间即依照时间，按照当时规则写述和巡逻。' },
      { id: 'sec-17', num: 17, title: '萝卜干', content: '萝卜干很好吃，但要少量。员工做菜不服合胃口的可以上报给部长解决。' },
      { id: 'sec-18', num: 18, title: '双人房', content: '病房是双人房，但病人眼中是单人房，如果有病人突然认为此是双人房时，请恭喜他，他可以出院了，你只需见证他的喜悦即可。' },
      { id: 'sec-19', num: 19, title: '听不懂的话', content: '如若病人在说一些你听不懂的东西，那么你可以上报给部长解决。' },
      { id: 'sec-20', num: 20, title: '植物园', content: '当病人去往植物园时，动物们会暴动，因此请不要此时离开动物园。' },
      { id: 'sec-21', num: 21, title: '承诺', content: '我们永远不会伤害您。' }
    ]
  }
];
